[REQ-sharing-geolocation]
text = '''
Users should be able to find medias to lend near their location.

When searching for medias, their location will only be given at the city level
and not more precisely to keep the privacy of users.
'''

[REQ-sharing-exchange]
text = '''
Users should exchange physically the medias.

It implies users should agree to a location where to do the trade.

Both users can then proceed the exchange by knowing the state of each media.

Currently there is no guarantee about a good experience when lending medias.
'''

[REQ-sharing-meeting]
text = '''
Users going to exchange things will set up their meeting point through a chat
(email?).

Discussing before about a meeting point allows users to meet at any location
without having to give some personal address.
'''
